version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    groups:
      all:
        # bump minor and patch updates
        minor:
          patterns:
            - "*"
          update-types:
            - "minor"
            - "patch"
    # stop major updates
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"