version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # bump minor and patch updates
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # stop major updates
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"