spring.application.name=rainbow
server.servlet.context-path=/api/v2
# rainbow details
rainbow.data.campuses-file=classpath:/data/campuses.json
rainbow.source.api=https://www.sis.hawaii.edu:9350/crseavail/api
rainbow.source.api.endpoint.subjects=/subjects