spring.application.name=rainbow
server.servlet.context-path=/api/v2
spring.jackson.property-naming-strategy=SNAKE_CASE

# rainbow details
rainbow.data.campuses-file=classpath:/data/campuses.json
rainbow.banner.api.max-concurrent-batches=3
rainbow.banner.api=https://www.sis.hawaii.edu:9350/crseavail/api
rainbow.banner.api.endpoint.subjects=/subjects
rainbow.banner.api.endpoint.courses=/courses
rainbow.banner.api.endpoint.course-desc=/course-desc
rainbow.banner.api.endpoint.course-grading=/course-grading
rainbow.banner.api.endpoint.section-desc=/section-desc
rainbow.banner.api.endpoint.section-notes=/section-notes
rainbow.banner.api.endpoint.section-attrib=/section-attrib
rainbow.banner.api.endpoint.section-counts=/section-counts
rainbow.banner.api.endpoint.base-section=/base-section
rainbow.banner.api.endpoint.meetings=/meetings