spring.application.name=starlite
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
server.servlet.context-path=/api/v2
spring.jackson.property-naming-strategy=SNAKE_CASE

# starlite details
starlite.data.campuses-file=classpath:/data/campus_codes.json
starlite.banner.api.max-concurrent-batches=3
starlite.banner.api=https://www.sis.hawaii.edu:9350/crseavail/api
starlite.banner.api.endpoint.subjects=/subjects
starlite.banner.api.endpoint.courses=/courses
starlite.banner.api.endpoint.course-desc=/course-desc
starlite.banner.api.endpoint.course-grading=/course-grading
starlite.banner.api.endpoint.section-desc=/section-desc
starlite.banner.api.endpoint.section-notes=/section-notes
starlite.banner.api.endpoint.section-attrib=/section-attrib
starlite.banner.api.endpoint.section-counts=/section-counts
starlite.banner.api.endpoint.base-section=/base-section
starlite.banner.api.endpoint.meetings=/meetings